### ISSUE TITLE
只能在本地使用？

### ISSUE THREAD

**Issue by tulip33** [admpub/nging#2]
不能在服务器端管理站点吗？
在win10下布置好了，可以出现管理界面。

**Comment by tulip33** [comment]
服务器Debian9，装了go git环境，都加了路径变量，但是执行go get github.com/admpub/nging 没反应

**Comment by tulip33** [comment]
在profile尾部添加了路径
export GOROOT=/usr/local/go
export PATH=$PATH:/usr/local/go/bin
PATH=$PATH:/usr/local/git/bin

**Comment by admpub** [comment]
> 在profile尾部添加了路径
> export GOROOT=/usr/local/go
> export PATH=$PATH:/usr/local/go/bin
> PATH=$PATH:/usr/local/git/bin

最后面一行少了一个`export`?
