### ISSUE TITLE
云服务可以添加webdav吗？

### ISSUE THREAD

**Issue by mymine** [admpub/nging#318]
内容同标题。云服务可以添加webdav吗？

**Comment by admpub** [comment]
感觉没有必要，因为效率不高，上传文件文件时的流程如下：
`WebDav客户端` ==[连接Nging对云服务提供的WebDav地址，上传文件到] => `Nging所在服务器` ==[Nging再上传到]=> `云服务器`
也就是文件会需要通过Nging所在的服务器进行中转
如果云服务商支持WebDav，不如直接在客户端使用云服务商提供的WebDav地址。

**Comment by mymine** [comment]
好的。
