### ISSUE TITLE
nging建议

### ISSUE THREAD

**Issue by zazaji** [admpub/nging#373]
nging是一个很棒的app。前段时间在找一个服务器管理的软件，找到nging，用的还不错。
在使用过程中有几条使用建议，
1、左侧的功能菜单能否做成按需配置，不用的功能可以通过配置文件隐藏或不启用？比如云服务基本用不到，是否可以删除。
2、服务器文件上传和管理，不是很方便，上传文件只有txt能编辑，而如果在管理服务器时，经常需要修改python等文件，建议增加可配置用编辑器打开的文件类型。
（可参考bt面板）
3、计划任务管理，可以增加一个立即执行的按钮，测试当前的任务执行是否有效。

**Comment by admpub** [comment]
感谢您的建议。目前你所说的这三种情况都是支持的。
分别说明如下：
1. 对于user_id=1的用户是默认的系统创始人，所有菜单都能看到的。可以通过单独创建一个用户，并分配一个角色来指定这个用户的权限，对于该用户来说，没有权限的页面不会显示相应的页面菜单，如果依然显示了要么是权限设置不正确，要么是程序bug；
2. 可以修改配置文件`config/config.yaml`中的`editableFileExtensions`节点内的值指定支持在线编辑的文件扩展名；
3. 计划任务是支持立即执行的（在不启动的情况下会显示一个类似于播放键的按钮，此按钮就是立即执行操作）

**Comment by zazaji** [comment]
非常感谢。都找到了对应的功能。
文件管理现在是一个默认的目录地址，能否更换到其他目录？

**Comment by admpub** [comment]
你是指离线下载里面的文件管理还是针对你整个服务器的文件管理？
1. 离线下载的文件目录跟上面一样也是在配置文件中进行设置；
2. 如果要对你的整个服务器的文件进行管理可以采用ssh管理里面的功能，在里面添加当前服务器的ssh账号就可以在网页上用sftp的方式管理当前服务器的所有文件了

**Comment by zazaji** [comment]
离线下载里面的文件管理，我在config.yml中未找到配置行

**Comment by admpub** [comment]
在配置文件的download节点，设置savePath

**Comment by zazaji** [comment]
谢谢，搞定
