### ISSUE TITLE
有没有路过的大佬做个docker镜像上传23333

### ISSUE THREAD

**Issue by SoraKasvgano** [admpub/nging#378]
感觉很适合在树莓派、N1上跑

默认自带的安装方式已经很简便，但是如果有docker镜像一键部署就更爽了23333

**Comment by admpub** [comment]
欢迎pr 😃

**Comment by admpub** [comment]
我已经在树莓派上跑很长时间了 😃

**Comment by SoraKasvgano** [comment]
> 我已经在树莓派上跑很长时间了 😃

dalao我遇到个奇怪的问题

在建站fast-cgi设置的时候

使用oneinstack安装的php可以完美运行  /tmp/shm/php-fpm.sock


但是使用军哥lnmp1.8 脚本安装的php7.4  /tmp/php-cgi.sock就会出现No input file specified ，静态文件可以，只有php文件有问题，可以确定php安装没问题，用nginx可以正常跑。

试了谷歌上的很多方法 都不行。。。不知道咋回事2333.。。

**Comment by admpub** [comment]
> > 我已经在树莓派上跑很长时间了 😃
> 
> 
> 
> dalao我遇到个奇怪的问题
> 
> 
> 
> 在建站fast-cgi设置的时候
> 
> 
> 
> 使用oneinstack安装的php可以完美运行  /tmp/shm/php-fpm.sock
> 
> 
> 
> 
> 
> 但是使用军哥lnmp1.8 脚本安装的php7.4  /tmp/php-cgi.sock就会出现No input file specified ，静态文件可以，只有php文件有问题，可以确定php安装没问题，用nginx可以正常跑。
> 
> 
> 
> 试了谷歌上的很多方法 都不行。。。不知道咋回事2333.。。

可以尝试从路径和权限这两方面去排查

**Comment by olddaigithub** [comment]
同求docker😀

**Comment by VisualSinger** [comment]
同求docker😀

**Comment by admpub** [comment]
已经增加 docker 镜像：
https://hub.docker.com/r/admpub/nging
