### ISSUE TITLE
可以集成ddns-go的域名解析服务吗？ 

### ISSUE THREAD

**Issue by Avey777** [admpub/nging#379]
刚看到nging的功能，感觉很强大；很希望将动态域名解析的功能也集成在一起，这样更方便使用了
参考地址：https://github.com/jeessy2/ddns-go/

**Comment by admpub** [comment]
好的，我研究一下

**Comment by SoraKasvgano** [comment]
> 好的，我研究一下

可以参考这两位的源码2333

https://github.com/NewFuture/DDNS
这个是go写的https://github.com/jeessy2/ddns-go

**Comment by admpub** [comment]
@SoraKasvgano @Avey777 DDNS功能已经发布在v3.6.0版本中
