### ISSUE TITLE
Frp服务器无法连接

### ISSUE THREAD

**Issue by chendx-github** [admpub/nging#387]
2021/09/24 18:41:31 [W] [service.go:104] login to server failed: EOF
2021/09/24 18:41:41 [W] [service.go:104] login to server failed: EOF
2021/09/24 18:41:51 [W] [service.go:104] login to server failed: EOF

以上是远程客户端信息
我启动了服务器  还有本地的客户端
但是远程 的客户端连不上 测试了很多次
端口都是联通的  防火墙已经关闭

**Comment by admpub** [comment]
可以查看服务端的日志，看看有什么提示

**Comment by 15091654146** [comment]
服务器上没有任何日志

**Comment by admpub** [comment]
在客户端电脑上ping的通服务器吗？

**Comment by 15091654146** [comment]
端口什么的都是没问题的  我用了tcp通信工具都测试了

**Comment by 15091654146** [comment]
但是今天我去看有显示连接成功了
2021/09/25 18:33:40 [W] [service.go:104] login to server failed: EOF
2021/09/25 18:33:50 [I] [service.go:304] [e99e4985e3c5cb26] login to server success, get run id [e99e4985e3c5cb26], server udp port [0]


这是正常的还是BUG  我用frp的时候一般都是直接就连接成功了

**Comment by admpub** [comment]
只要确定配置没有问题的话，就要看看服务端有没有成功启动。
配置、网络和服务端正常启动这三者都满足一般不会有问题

**Comment by 15091654146** [comment]
我这个问题怪异在于 当时配置的时候怎么弄都不成功  只有在过了一段时间之后才会连接上  而且这个时间还比较长
我开了两个服务两个客户端
从 09-25 15:07:30  我重启了服务
到 09/25 16:39:17  A机器连接到了B机器的服务端
另一个是 09/25 18:33:50  B机器连接到了A的服务端
两个连接时间又差了这么多 应该是不正常
我在本地测试都是OK的  一瞬间就连接上了

**Comment by admpub** [comment]
你那个场景有点复杂。我本地连接远程vps服务器上的服务端也是一连就成功。

**Comment by 15091654146** [comment]
嗯  好吧 可能是我哪里配置的有问题  也有可能是网络原因
我还有一个题外问题  就是如何编译  我在编译的时候不知道怎么带上  bindata
请指教
PS D:\GO\demo\nging> go build bindata_nging.go
# command-line-arguments
.\bindata_nging.go:28:18: undefined: Asset
.\bindata_nging.go:29:21: undefined: AssetDir
.\bindata_nging.go:30:22: undefined: AssetInfo

**Comment by chendx-github** [comment]
我在linux下执行成功了  windows 有的命令不支持

**Comment by chendx-github** [comment]
连接较慢  不影响功能

**Comment by admpub** [comment]
go build -tags bindata
跨平台编译使用tool文件夹里的build-by-xgo.sh来编译
