### ISSUE TITLE
网络不好时会导致程序cpu占用拉满

### ISSUE THREAD

**Issue by chendx-github** [admpub/nging#392]
十一假期期间应该是网络或者内存出问题了 导致 进程的cpu爆满
应该是个循环有问题  我没有仔细检查具体是哪里的问题

**Comment by admpub** [comment]
是哪个版本？

**Comment by chendx-github** [comment]
master 最新版本  7e81067879640c412a3a2eea61ea0cdcea7f8e2f

**Comment by admpub** [comment]
当时启用了nging里面的哪些功能？计划任务？DDNS？等等都列一下。或者你的初步估计是哪一部分功能造成的？也提供一下系统名称和数据库类型。

因为你提供的信息太少，我无从判断问题所在，需要缩小范围。
目前自用没有出现这样的问题。

**Comment by chendx-github** [comment]
数据库 sqlite

**Comment by admpub** [comment]
上面的那个是客户端的日志吧？
是服务端的CPU占用爆满还是客户端？

**Comment by chendx-github** [comment]
是客户端日志
也是客户端爆了

**Comment by admpub** [comment]
关于frp客户端在异常网络情况下可能出现的CPU占用高的问题，要等待frp官方后续优化了，本仓库会同步更新

**Comment by ywzhaiqi** [comment]
同样问题，4.0.0。20分钟内出现2次 cpu 100%，网页服务全部停止访问，重启服务才结果。
有一次是在离线下载 - 文件管理时出现，但重启后再次访问又无此问题。

提个小建议：
能否让 caddy 服务分离，这样就算 nging 卡主，网页服务也正常

**Comment by admpub** [comment]
目前的caddy是以单独的程序进程启动的。可以编译仓库里最新的代码试试看。目前我还没有遇到你所说的情况。欢迎提供更多的可重现细节。





------------------ 原始邮件 ------------------
发件人: ywzhaiqi ***@***.***&gt;
发送时间: 2022年2月9日 20:43
收件人: admpub/nging ***@***.***&gt;
抄送: Hank Shen ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [admpub/nging] 网络不好时会导致程序cpu占用拉满 (#392)





 
同样问题，4.0.0。20分钟内出现2次 cpu 100%，网页服务全部停止访问，重启服务才结果。
 有一次是在离线下载 - 文件管理时出现，但重启后再次访问又无此问题。
 
提个小建议：
 能否让 caddy 服务分离，这样就算 nging 卡主，网页服务也正常

**Comment by DefiedParty** [comment]
ddnsv6会引起主程序卡死，cpu持续占用
```
779508|2023-07-09 19:54:14|Debug|app|[DDNS] 查询到ipv6变更:  => 2ffff:ffff:ffff:ffff::ffff
fatal error: unexpected signal during runtime execution
```

**Comment by admpub** [comment]
> 

是什么系统？

**Comment by DefiedParty** [comment]
> @DefiedParty 是什么系统？

Armbian 5.15.92-flippy-81+o

**Comment by chendx-github** [comment]
赶紧这个应该不是frp的问题，在frp的使用过程中我还没发现过这种问题

**Comment by DefiedParty** [comment]
是的，这个是ddns引起的，因为我没有使用frp

**Comment by admpub** [comment]
> > @DefiedParty 是什么系统？
> 
> Armbian 5.15.92-flippy-81+o
估计是go语言的net库不兼容这个系统。稍等，我编译一个新版本你试试

**Comment by admpub** [comment]
@DefiedParty 试试 `v5.1.1-beta1` ：https://dl.webx.top/nging/v5.1.1-beta1/

**Comment by DefiedParty** [comment]
> 

解决了，赞👍

**Comment by admpub** [comment]
@chendx-github 这个问题（CPU100%占用）在新版中是否还存在？

**Comment by chendx-github** [comment]
似乎没遇到过了，我从那以后就没有使用自带的frp所以具体有没有解决也不是很确定，但是没有遇到过cpu100的情况了
