### ISSUE TITLE
hi 请问nging中的frpc版本是多少呢

### ISSUE THREAD

**Issue by ziimee** [admpub/nging#4]
尝试链接启动，都不成功，不知道是不是版本不兼容服务器的frps版本
2020/01/01 09:31:11 [I] [service.go:223] login to server success, get run id [5736bce10bd09b6b], server udp port [6667]
2020/01/01 09:31:11 [I] [proxy_manager.go:137] [5736bce10bd09b6b] proxy added: [yaitoo23.ssh]
2020/01/01 09:31:11 [I] [service.go:223] login to server success, get run id [7c5a565ecd11dd15], server udp port [6667]
2020/01/01 09:31:11 [I] [proxy_manager.go:137] [7c5a565ecd11dd15] proxy added: [woshiyonghubiaos.ssh]
2020/01/01 09:31:11 [W] [control.go:207] read error: message type error
2020/01/01 09:31:11 [I] [control.go:228] control writer is closing
2020/01/01 09:31:11 [I] [service.go:129] try to reconnect to server...
2020/01/01 09:31:11 [W] [control.go:207] read error: message type error
2020/01/01 09:31:11 [I] [control.go:228] control writer is closing
2020/01/01 09:31:11 [I] [service.go:129] try to reconnect to server...

**Comment by admpub** [comment]
v0.28.0

**Comment by ziimee** [comment]
> v0.28.0

我在服务端搭了0.28.0对应版本报错信息，nging里的 frpc还是一样报错日志：
2020/01/06 02:10:49 [I] [service.go:223] login to server success, get run id [452e6bb557c37033], server udp port [7801]
2020/01/06 02:10:49 [I] [proxy_manager.go:137] [452e6bb557c37033] proxy added: [wwwb.ssh]
2020/01/06 02:10:49 [W] [control.go:207] read error: message type error
2020/01/06 02:10:49 [I] [control.go:228] control writer is closing
2020/01/06 02:10:49 [I] [service.go:129] try to reconnect to server...
2020/01/06 02:10:49 [I] [service.go:223] login to server success, get run id [452e6bb557c37033], server udp port [7801]
2020/01/06 02:10:49 [I] [proxy_manager.go:137] [452e6bb557c37033] proxy added: [wwwb.ssh]
2020/01/06 02:10:49 [W] [control.go:207] read error: message type error
2020/01/06 02:10:49 [I] [control.go:228] control writer is closing
2020/01/06 02:10:49 [I] [service.go:129] try to reconnect to server...
服务端frps日志：
2020/01/06 10:18:33 [I] [service.go:356] client login info: ip [117.55.217.153:46380] version [0.28.0] hostname [] os [linux] arch [amd64]
2020/01/06 10:18:33 [W] [control.go:303] [077bca0a6332c39f] read error: message type error
2020/01/06 10:18:33 [I] [control.go:274] [077bca0a6332c39f] control writer is closing
2020/01/06 10:18:33 [I] [control.go:350] [077bca0a6332c39f] client exit success
2020/01/06 10:18:33 [I] [service.go:356] client login info: ip [117.55.217.153:46382] version [0.28.0] hostname [] os [linux] arch [amd64]

**Comment by admpub** [comment]
nging中的frp是在官方源码的基础上做了一些修改，所以会跟官方原版有些不兼容，不能交叉使用。
"在frp组带入服务端信息"这段话我不太能理解，frp中的分组是可以同时分配给多个服务端和客户端的，不适合在里面添加配置信息。配置列表页中的复制功能也许可以解决您的问题

**Comment by ziimee** [comment]
复制可以解决创建的问题，但是发生变动的话，就会需要一个个去修改，所以我设想分组带有服务器信息（地址、端口、token：
![image](https://user-images.githubusercontent.com/22512985/72196920-d0045c80-3456-11ea-8c1f-49ca95854225.png)
）；我现在用的appnode管理的方式比较便捷，但是缺少多服务器组概念，故无法在客户端连多个服务器。
