### ISSUE TITLE
内网穿透-多用户支持

### ISSUE THREAD

**Issue by wanrenzhizun** [admpub/nging#404]
请问一下大佬，我开启服务端多用户支持插件，但是客户端连接不成功，服务端没有启用http://127.0.0.1:8080
2021/11/10 15:16:40 [I] [frp_server.go:202] Start frps success
2021/11/10 15:16:42 [W] [manager.go:83] [reqid: 178c991991baf0f0] send Login request to plugin [multiuser_login] error: Post "http://127.0.0.1:8080/frp_login?op=Login&version=0.1.0": dial tcp 127.0.0.1:8080: connectex: No connection could be made because the target machine actively refused it.
2021/11/10 15:16:42 [W] [service.go:351] register control error: send Login request to plugin error

这是什么情况？

**Comment by admpub** [comment]
配置frp帐号和后台地址了吗？
可以自己访问一下那个地址是否畅通

**Comment by wanrenzhizun** [comment]
配置了的，那个地址访问不了，我查询端口也没有使用8080的端口

**Comment by wanrenzhizun** [comment]
<img width="815" alt="2021-11-10_201116" src="https://user-images.githubusercontent.com/31756438/141110801-60ec4e4a-b315-49cb-b04a-0368182c067a.png">

**Comment by admpub** [comment]
127.0.0.1:8080是没有设置后台时默认的一个地址，这个地址不一定有效，是在代码里写死的。所以要在后台配置一个你自己的地址。
如果配置了后台地址后依然没有生效，可以尝试重启一下程序

**Comment by wanrenzhizun** [comment]
那multiuser_login服务是需要自己启动一个么？

**Comment by wanrenzhizun** [comment]
配置了后台地址，重启整个服务或者frp服务，还是访问的127.0.0.1:8080

**Comment by admpub** [comment]
不需要单独启动，跟nging是一体的





------------------ 原始邮件 ------------------
发件人: wanrenzhizun ***@***.***&gt;
发送时间: 2021年11月11日 11:46
收件人: admpub/nging ***@***.***&gt;
抄送: Hank Shen ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [admpub/nging] 内网穿透-多用户支持 (Issue #404)






那multiuser_login服务是需要自己启动一个么？

**Comment by wanrenzhizun** [comment]
ok，谢谢大佬
