### ISSUE TITLE
以服务方式启动时如何修改端口

### ISSUE THREAD

**Issue by zhengmingliang** [admpub/nging#406]
`./nging service start` 时，默认启动端口是 9999
我使用 `nging service start -p 8141` ，使用的也是默认端口，未能使用新端口，`config/config.yaml` 文件中未发现启动时端口的配置

**Comment by admpub** [comment]
```
./nging service install -p 8141
```
安装服务的时候添加所需参数。如果已经安装过服务了，用命令`./nging service uninstall`卸载服务后重新带上自己的参数执行以上命令
