### ISSUE TITLE
文件管理后续有规划支持文件夹上传和文件分享的功能吗？

### ISSUE THREAD

**Issue by Avey777** [admpub/nging#408]
![image](https://user-images.githubusercontent.com/35259040/144700815-58dc1b55-eb3a-44b2-8c43-fc7c39294502.png)

**Comment by admpub** [comment]
暂无计划支持文件夹上传。
文件分享可以采用在”网站管理“里面将需要分享的目录作为网站的目录并开启“文件服务”功能来实现。也可以在“网站管理”里面设置webdav来控制访问权限
