### ISSUE TITLE
多台服务器可以集中管理吗？

### ISSUE THREAD

**Issue by imnotprogrammer** [admpub/nging#413]
提出这种问题，是因为我遇到的场景有很多台服务器，按照我对这个工具的了解，是需要对每台服务器安装nging,，这样对我或者对和我面对同样场景的用户来说，依然管理繁琐，正如你所料，这样的场景面对不断的切换登录，而且要记录大量的密码。所以说，我想咨询拥有那种集中管理多台服务器的功能吗？最后感谢你开源，因为其确实为我带来了巨大的帮助。希望得到你的答复！祝你生活愉快！

**Comment by admpub** [comment]
不支持哦。目前仅支持管理单台服务器。
