### ISSUE TITLE
内网穿透无法使用命令

### ISSUE THREAD

**Issue by sunnynie** [admpub/nging#448]
内网穿透无法使用命令

**Comment by admpub** [comment]
请详细描述

**Comment by sunnynie** [comment]
内网穿透,没有开启tcp,能不能扩展,ssh2http 的功能

**Comment by admpub** [comment]
> 内网穿透,没有开启tcp,能不能扩展,ssh2http 的功能

因为是基于frp，如果frp本身不支持，那就是不支持的
