### ISSUE TITLE
[BUG]数据库查看会乱跳

### ISSUE THREAD

**Issue by 4867896** [admpub/nging#462]
**问题描述**
数据库表查看界面，滑动到底部会一直上下跳动。

**重现步骤**
重现步骤如下:
1. 前往 'Home >MySQL管理  > ADMIN数据库   >数据库: USER > 表: USERS > 数据'   数据条数 25条
2. 滚动到 '底部'
3. 出现上下跳动

**期望的正确结果**
可以正确滑动到底部

**系统类型和版本:**
浏览器
Microsoft Edge
版本 89.0.774.63 (官方内部版本) (64 位)

Chrome 
版本 80.0.3987.149（正式版本） （64 位）
Included Chrome++ 1.0.3

2022 Nging v4.1.2 licensed

**数据库类型和版本:**
 - MySQL8.0

**Comment by admpub** [comment]
我专门找了一个chrome87的试了，没有出现你说的问题，我的是macos系统。
不知道你的是什么系统，可以把浏览器更新到最新版本试试
