### ISSUE TITLE
[BUG]SQLITE安装失败

### ISSUE THREAD

**Issue by chendx-github** [admpub/nging#464]
**问题描述**
安装失败
SQLITE数据库

**重现步骤**
重现步骤如下:
安装失败

**截图**
![image](https://user-images.githubusercontent.com/55473491/173006852-b66d15f5-6717-42cb-95fd-9a5160dfc254.png)

![image](https://user-images.githubusercontent.com/55473491/173006506-8752b679-cf4a-4773-b3b8-0c4930a8d668.png)

**系统类型和版本:**
 - 64位windows11，64winservers2012

**其它相关信息**
输入有关此问题的其它说明
        Context:        context.Background

31120|2022-06-10 14:40:31|Info|app|[installer]Generate a security key
31120|2022-06-10 14:40:31|Info|app|[installer]Save the configuration file
[Register Extend Config] P31120 wanIPProvider: *ip2region.WANIPProviders
31120|2022-06-10 14:40:31|Info|app|Start reloading configuration file: D:\sof\nging_windows_amd32\config\config.yaml
31120|2022-06-10 14:40:31|Info|app|[installer]Generated file: D:\sof\nging_windows_amd32\installed.lock
[Register Extend Config] P31120 upload: *upload.Config
[Register Extend Config] P31120 download: *config.Config
[Register Extend Config] P31120 ftpserver: *ftp.Config
[Register Extend Config] P31120 caddy: *caddy.Config
panic: assignment to entry in nil map

goroutine 52 [running]:
github.com/admpub/nging/v4/application/library/upload.(*Config).Init(0x17f2c0f0)
        /source/application/library/upload/config.go:152 +0x102
github.com/admpub/nging/v4/application/library/upload.(*Config).SetDefaults(0x17f2c0f0)
        /source/application/library/upload/config.go:145 +0x21
github.com/admpub/nging/v4/application/library/config.(*Config).SetDefaults(0x17eb2000, {0x17e859b0, 0x2d})
        /source/application/library/config/config.go:264 +0x1f7
github.com/admpub/nging/v4/application/library/config.InitConfig()
        /source/application/library/config/util.go:87 +0x303
github.com/admpub/nging/v4/application/library/config.ParseConfig()
        /source/application/library/config/util.go:103 +0x1e
github.com/admpub/nging/v4/application/initialize/backend.DefaultConfigWatcher.func1({0x1852ad20, 0x2d})
        /source/application/initialize/backend/helper.go:64 +0x107
github.com/admpub/nging/v4/application/library/config.WatchConfig.func1({0x1852ad20, 0x2d})
        /source/application/library/config/watcher.go:37 +0x11e
github.com/webx-top/com.(*MonitorEvent).listen(0x17efb680)
        /source/vendor/github.com/webx-top/com/monitor.go:193 +0x296
created by github.com/webx-top/com.(*MonitorEvent).backendListen
        /source/vendor/github.com/webx-top/com/monitor.go:112 +0x5a

**Comment by admpub** [comment]
谢谢反馈。最近的一个提交已经修复了这个问题

**Comment by admpub** [comment]
已经在v4.1.3版修复
