### ISSUE TITLE
[BUG]Sqlite安装报错 但是能用 用的时候有的会闪退

### ISSUE THREAD

**Issue by chendx-github** [admpub/nging#469]
**问题描述**
Sqlite安装报错 但是能用 用的时候有的会闪退

**重现步骤**
重现步骤如下:
安装到最后 100%

**截图**
![image](https://user-images.githubusercontent.com/55473491/174703671-cbc1289f-9591-4c2b-8b6c-1e939dd15e5f.png)

**系统类型和版本:**
 - 64位windows10

**数据库类型和版本:**
 - sqlite

**其它相关信息**
[PANIC RECOVER] runtime error: invalid memory address or nil pointer dereference /usr/local/go/src/runtime/panic.go:838 /usr/local/go/src/runtime/panic.go:220 /usr/local/go/src/runtime/signal_windows.go:255 /usr/local/go/src/database/sql/sql.go:1290 /usr/local/go/src/database/sql/sql.go:1869 /usr/local/go/src/database/sql/sql.go:1847 /source/vendor/github.com/webx-top/db/internal/sqladapter/compat/query_go18.go:71 /source/vendor/github.com/webx-top/db/sqlite/database.go:197 /source/vendor/github.com/webx-top/db/internal/sqladapter/database.go:489 /source/vendor/github.com/webx-top/db/lib/sqlbuilder/insert.go:160 /source/vendor/github.com/webx-top/db/lib/sqlbuilder/insert.go:152 /source/vendor/github.com/webx-top/db/sqlite/collection.go:77 /source/vendor/github.com/webx-top/db/lib/factory/transaction.go:277 /source/vendor/github.com/webx-top/db/lib/factory/param.go:671 /source/application/dbschema/NgingConfig.go:340 /source/application/registry/settings/config_default.go:326 /source/application/handler/setup/setup.go:297 /source/vendor/github.com/webx-top/echo/echo.go:104 /source/vendor/github.com/webx-top/echo/context_x_base.go:119 /source/vendor/github.com/webx-top/echo/middleware/render/middleware.go:93 /source/vendor/github.com/webx-top/echo/echo.go:104 /source/application/middleware/funcmap.go:232 /source/vendor/github.com/webx-top/echo/echo.go:104 /source/application/middleware/funcmap.go:165 /source/vendor/github.com/webx-top/echo/echo.go:104 /source/application/initialize/backend/backend_middleware.go:13 /source/vendor/github.com/webx-top/echo/echo.go:104 /source/vendor/github.com/webx-top/echo/middleware/funcmap.go:35

**Comment by admpub** [comment]
@chendx-github 好的，提供的报错信息很有用，我排查一下

**Comment by admpub** [comment]
已在 v4.1.4 修复
