### ISSUE TITLE
[BUG]win2016服务器启动服务失败

### ISSUE THREAD

**Issue by chendx-github** [admpub/nging#474]
**问题描述**
win2016服务器启动服务失败
但是我去直接执行 .\nging service run 却是可以运行的
**重现步骤**
重现步骤如下:
启动服务

**系统类型和版本:**
 - 64位win2016

**数据库类型和版本:**
 - sqlite

**其它相关信息**
nging service start
[Register Extend Config] P4244 ftpserver: *ftp.Config
[Register Extend Config] P4244 caddy: *caddy.Config
[Register Extend Config] P4244 wanIPProvider: *ip2region.WANIPProviders
[Register Extend Config] P4244 upload: *upload.Config
[Register Extend Config] P4244 download: *config.Config
[ INFO]4244|2022-06-22 13:30:19|Info|db|<master>
        Session ID:     00001
        Query:          PRAGMA TABLE_INFO('nging_config')
        Time taken:     0.00000s
        Context:        context.Background

[ INFO]4244|2022-06-22 13:30:19|Info|db|<master>
        Session ID:     00001
        Query:          SELECT * FROM "nging_config" WHERE ("disabled" = 'N')
        Arguments:      ["N"]
        Time taken:     0.00106s
        Context:        context.Background

[ INFO]4244|2022-06-22 13:30:19|Info|app|Currently running in normal mode
Error: Failed to start Nging: The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.
4244|2022-06-22 13:30:19|Error|service|start: Failed to start Nging: The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.
Failed to start Nging: The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.

**Comment by admpub** [comment]
已在 v4.1.4 修复

**Comment by chendx-github** [comment]
The service did not respond to the start or control request in a timely fashion.
10080|2022-07-02 10:56:22|Error|service|start: Failed to start Nging: The service did not respond to the start or control request in a timely fashion.
Failed to start Nging: The service did not respond to the start or control request in a timely fashion.

**Comment by chendx-github** [comment]
还是不可以啊

**Comment by chendx-github** [comment]
我用的sftpgo也是用的这种模式  都是可以正常启动的

**Comment by admpub** [comment]
@chendx-github 目前服务采用的是 github.com/kardianos/service 这个包，兼容性不太完美，后面有时间了我看看有没有更好的替换掉它

**Comment by admpub** [comment]
> 

不知道这篇文章对你的问题有否有用：[How to Fix Error 1053: The Service did not Respond to the Start or Control Request in a Timely Fashion?](https://appuals.com/how-to-fix-error-1053-the-service-did-not-respond-to-the-start-or-control-request-in-a-timely-fashion/#:~:text=How%20to%20Fix%20Error%201053%3A%20The%20Service%20did,System%20File%20Corruptions.%20Another%20thing%20to%20try%20)
你可以参考一下

**Comment by chendx-github** [comment]
好的谢谢

**Comment by chendx-github** [comment]
https://github.com/drakkan/sftpgo/tree/main/service
可不可以参考这个

**Comment by chendx-github** [comment]
github.com/drakkan/sftpgo/v2/service

**Comment by admpub** [comment]
@chendx-github 可以试试 [v4.1.5](https://dl.webx.top/nging/v4.1.5/)，升级了 service 包到最新版

**Comment by chendx-github** [comment]
错误87:参数错误

**Comment by chendx-github** [comment]
nging.exe service start
[Register Extend Config] P30816 caddy: *caddy.Config
[Register Extend Config] P30816 wanIPProvider: *ip2region.WANIPProviders
[Register Extend Config] P30816 upload: *upload.Config
[Register Extend Config] P30816 download: *config.Config
[Register Extend Config] P30816 ftpserver: *ftp.Config
[ INFO]30816|2022-07-03 15:48:52|Info|app|Currently running in debug mode
Error: Failed to start Nging: The parameter is incorrect.
Failed to start Nging: The parameter is incorrect.

**Comment by admpub** [comment]
> nging.exe service start [Register Extend Config] P30816 caddy: *caddy.Config [Register Extend Config] P30816 wanIPProvider: *ip2region.WANIPProviders [Register Extend Config] P30816 upload: *upload.Config [Register Extend Config] P30816 download: *config.Config [Register Extend Config] P30816 ftpserver: *ftp.Config [ INFO]30816|2022-07-03 15:48:52|Info|app|Currently running in debug mode Error: Failed to start Nging: The parameter is incorrect. Failed to start Nging: The parameter is incorrect.

程序已经更新，重新下载即可

**Comment by chendx-github** [comment]
还是4.15吗 我看时间没有变啊
还是
07/03/2022 05:38:15
这个时间
我前面测试的就是4.1.5的的程序

**Comment by admpub** [comment]
> 还是4.15吗 我看时间没有变啊
> 
> 还是
> 
> 07/03/2022 05:38:15
> 
> 这个时间
> 
> 我前面测试的就是4.1.5的的程序

是的

**Comment by chendx-github** [comment]
那就还是有问题  只是错误内容变了

**Comment by admpub** [comment]
> 那就还是有问题  只是错误内容变了

只有等 service 包修复了，或者采用 docker 来运行

**Comment by chendx-github** [comment]
我现在使用的是任务计划启动的也可以用
