### ISSUE TITLE
内存不足安装失败出现的一些问题

### ISSUE THREAD

**Issue by eternity-chen** [admpub/nging#475]
**问题描述**
我的阿里云主机安装时，内存低于2.2G时会导致安装失败，提示删除install.lock文件重新安装，将内存清理到2.2G并删除后install.lock文件后安装成功，但是install.lock文件并没有再次生成

**重现步骤**
重现步骤如下:
1. 安装机器的内存低于2.1G
2. 进入安装步骤
3. 安装失败提示删除install.lock文件，按照提示操作后安装成功，install.lock文件并没有再次生成
4. 再次重新启动程序又会进入安装步骤

**期望的正确结果**
安装成功后重启程序不会重新安装

**系统类型和版本:**
 - 64位ubuntu18

**数据库类型和版本:**
 - MySQL8.0

**其它相关信息**
部署程序版本：4.1.3

**Comment by eternity-chen** [comment]
错误信息如下
8371|2022-06-22 14:54:40|Error|echo|[PANIC RECOVER] runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:838
/usr/local/go/src/runtime/panic.go:220
/usr/local/go/src/runtime/signal_unix.go:818
/usr/local/go/src/database/sql/sql.go:1290
/usr/local/go/src/database/sql/sql.go:1732
/usr/local/go/src/database/sql/sql.go:1710
/source/vendor/github.com/webx-top/db/internal/sqladapter/compat/query_go18.go:39
/source/vendor/github.com/webx-top/db/internal/sqladapter/database.go:554
/source/vendor/github.com/webx-top/db/lib/sqlbuilder/select.go:483
/source/vendor/github.com/webx-top/db/lib/sqlbuilder/select.go:473
/source/vendor/github.com/webx-top/db/lib/sqlbuilder/paginate.go:175
/source/vendor/github.com/webx-top/db/internal/sqladapter/result.go:237
/source/vendor/github.com/webx-top/db/lib/factory/transaction.go:249
/source/vendor/github.com/webx-top/db/lib/factory/param.go:643
/source/application/dbschema/NgingConfig.go:309
/source/application/registry/settings/config_default.go:304
/source/application/handler/setup/setup.go:297
/source/vendor/github.com/webx-top/echo/echo.go:104
/source/vendor/github.com/webx-top/echo/context_x_base.go:119
/source/vendor/github.com/webx-top/echo/middleware/render/middleware.go:93
/source/vendor/github.com/webx-top/echo/echo.go:104
/source/application/middleware/funcmap.go:232
/source/vendor/github.com/webx-top/echo/echo.go:104
/source/application/middleware/funcmap.go:165
/source/vendor/github.com/webx-top/echo/echo.go:104
/source/application/initialize/backend/backend_middleware.go:13
/source/vendor/github.com/webx-top/echo/echo.go:104
/source/vendor/github.com/webx-top/echo/middleware/funcmap.go:35
/source/vendor/github.com/webx-top/echo/echo.go:104
/source/application/middleware/transaction.go:30
/source/vendor/github.com/webx-top/echo/echo.go:104
/source/vendor/github.com/webx-top/echo/middleware/validate.go:18
/source/vendor/github.com/webx-top/echo/echo.go:104
/source/vendor/github.com/webx-top/echo/middleware/language/language.go:172
/source/vendor/github.com/webx-top/echo/echo.go:104
/source/vendor/github.com/webx-top/echo/middleware/session/middleware.go:83
/source/vendor/github.com/webx-top/echo/echo.go:104
/source/vendor/github.com/webx-top/echo/middleware/bindata/bindata.go:33
/source/vendor/github.com/webx-top/echo/echo.go:104
/source/vendor/github.com/webx-top/echo/middleware/log.go:52
/source/vendor/github.com/webx-top/echo/echo.go:104
/source/application/middleware/request.go:28
/source/vendor/github.com/webx-top/echo/echo.go:104
/source/vendor/github.com/webx-top/echo/middleware/recover.go:68
/source/vendor/github.com/webx-top/echo/echo.go:104
/source/vendor/github.com/webx-top/echo/echo.go:724
/source/vendor/github.com/webx-top/echo/subdomains/subdomains.go:196
/source/vendor/github.com/webx-top/echo/engine/standard/server.go:150
/usr/local/go/src/net/http/server.go:2916
/usr/local/go/src/net/http/server.go:1966
/usr/local/go/src/runtime/asm_amd64.s:1571

**Comment by admpub** [comment]
已在 v4.1.4 修复
