### ISSUE TITLE
计划任务/ 任务管理 bug？！

### ISSUE THREAD

**Issue by ziimee** [admpub/nging#524]
根据提示：

> / 表示起始时间开始触发，然后每隔固定时间触发一次，例如在Minutes域使用5/20,则意味着在5分的时候开始触发一次，而25，45等分别触发一次。

当设置 * 5/30 * * * *
时间到的时候会 每秒执行。而不是 第 5 分 第35分
是我理解还是配置问题，还是bug呢

**Comment by admpub** [comment]
0 5/30 * * * *
这样
