### ISSUE TITLE
docker 文件映射是否需要改进？

### ISSUE THREAD

**Issue by jxjxjhjh** [admpub/nging#594]
示例docker写法的文件映射中没有Caddyfile config 等，以目前的文件映射，能否保存所有的数据，在重新docker run后恢复如初？

**Comment by admpub** [comment]
示例中有映射 myconfig 文件夹，Caddy 的配置位于 myconfig/vhosts 路径下，所以是会持久保存 Caddy 的配置的，就算重启 docker 也不会丢失。

**Comment by admpub** [comment]
我发现了一个问题：Caddyfile 这个文件里面引用的是 ./config/vhosts/*.conf 这个路径， 这样就没有用到 “myconfig/vhosts” 里的文件。需要再挂载一个自己的 Caddyfile 文件来解决，内容为：
```
import ./myconfig/vhosts/*.conf
```
文件挂载路径：/home/nging_linux_amd64/Caddyfile

**Comment by admpub** [comment]
我发现了一个问题：Caddyfile 这个文件里面引用的是 ./config/vhosts/*.conf 这个路径， 这样就没有用到 “myconfig/vhosts” 里的文件。需要再挂载一个自己的 Caddyfile 文件来解决，内容为：
```
import ./myconfig/vhosts/*.conf
```
文件挂载路径：/home/nging_linux_amd64/Caddyfile

**Comment by admpub** [comment]
已经在 v5.0.1 版本改进，执行 `docker pull admpub/nging:latest` 更新镜像。
