### ISSUE TITLE
5.0.1无法使用[BUG]

### ISSUE THREAD

**Issue by jxjxjhjh** [admpub/nging#605]
**问题描述**
添加网站无法访问，80和443都是，使用的是Nging + SQLite docker安装文件，原本里面没有开放80和443，只有9999，后来添加了80和443也没用。

**重现步骤**
Nging + SQLite docker 正常安装，正常添加网站。
监听地址填写 http://xxx.com:80
Proxy 后端代理地址填写 http://ip:端口

ip:端口 是可以正常访问的。

**期望的正确结果**
输入期望的正确结果

**截图**
这里提供截图

**系统类型和版本:**
 - 64位windows10

**数据库类型和版本:**
 - MySQL8.0

**其它相关信息**
输入有关此问题的其它说明

**Comment by admpub** [comment]
访问80端口报的是错误码多少？

**Comment by jxjxjhjh** [comment]
> 访问80端口报的错误码是多少？404还是502？ 可以试试在docker里直接访问你的proxy地址看看是否通畅

404。
docker访问 不知道怎么弄，浏览器输入被反代网站的 域名:端口 都是正常的

**Comment by admpub** [comment]
@jxjxjhjh 如果是需要反代到宿主机里的一个服务，并且对docker不熟练，建议直接在宿主机里启动nging，因为nging本身是绿色软件，不会给你的系统安装其它东西，直接使用更省心，避免去docker绕一圈
