### ISSUE TITLE
进程值守增加指定用户

### ISSUE THREAD

**Issue by chendx-github** [admpub/nging#617]
不同的用户有不同的权限
比如windows下有的用户可以进行网络操作，有的用户需要管理员权限

**Comment by chendx-github** [comment]
老大这个功能什么时候能加上？

**Comment by admpub** [comment]
> 老大这个功能什么时候能加上？

暂无计划。
在Windows下可以用runas命令以指定用户身份运行程序，你可以试一下

**Comment by chendx-github** [comment]
runas 命令需要手动输入密码  没办法自动配置

**Comment by admpub** [comment]
> runas 命令需要手动输入密码  没办法自动配置

nging需要以最高权限的administrator来运行，否则会有很多限制的

**Comment by chendx-github** [comment]
nging需要以最高权限administraoter  这个没有问题，我是想在进程值守哪里的配置项增加启动某个进程的时候使用指定账户来启动，否则没有办法取得用户的一些权限，比如配置文件在某个用户下面，或者smb的网络盘权限也是某一个用户的，而管理员administrator这个用户没有这些权限或者数据

**Comment by admpub** [comment]
> nging需要以最高权限administraoter  这个没有问题，我是想在进程值守哪里的配置项增加启动某个进程的时候使用指定账户来启动，否则没有办法取得用户的一些权限，比如配置文件在某个用户下面，或者smb的网络盘权限也是某一个用户的，而管理员administrator这个用户没有这些权限或者数据

我的理解是以最高权限启动nging后，nging里执行runas命令本身的时候也是超级管理员，而用ruanas指定其他用户的时候应该不需要密码吧？就像linux下用root身份执行sudo -u 来指定用户不需要这个用户的密码一样

**Comment by chendx-github** [comment]
windows不可以的

**Comment by chendx-github** [comment]
存在域这个概念

**Comment by admpub** [comment]
> windows不可以的
> 
> 

OK，了解具体场景了，最近我增加一下这方面的支持

**Comment by chendx-github** [comment]
[Process:16][2023-08-11T18:56:45+08:00]failed. fork/exec xxx.exe: A required privilege is not held by the client.
windows10 设置用户后报错了

**Comment by admpub** [comment]
> [Process:16][2023-08-11T18:56:45+08:00]failed. fork/exec xxx.exe: A required privilege is not held by the client.
> 
> windows10 设置用户后报错了

把 nging 安装为服务了吗？

**Comment by chendx-github** [comment]
用管理员启动的，但是这个应该不会影响，以某个用户启动这个功能，因为我也经常使用c#写 普通用户指定管理员启动都是可以的

**Comment by admpub** [comment]
> 用管理员启动的，但是这个应该不会影响，以某个用户启动这个功能，因为我也经常使用c#写 普通用户指定管理员启动都是可以的

有影响的。因为这里只支持按照服务的方式启动时的调用，nging 需要开机自动启动，所以安装为服务这个场景更为普遍和广泛

**Comment by chendx-github** [comment]
我确实是安装为服务的  我只是将服务启动设置为指定用户了
![image](https://github.com/admpub/nging/assets/55473491/1c4ba6a4-1805-4f5e-a696-a03c22165e9f)

**Comment by admpub** [comment]
> 我确实是安装为服务的  我只是将服务启动设置为指定用户了
> 
> ![image](https://github.com/admpub/nging/assets/55473491/1c4ba6a4-1805-4f5e-a696-a03c22165e9f)
> 
> 

那确实不行，需要选择“安装为本地系统账户”才行。其实用`nging service install`命令安装为服务就行了，不用手动去配置。

**Comment by chendx-github** [comment]
但是在windws上 nging service install 命令创建的服务根本没法启动，前段时期我跟你说过此事情，在另一个issuse里边https://github.com/admpub/nging/issues/474

**Comment by admpub** [comment]
> 但是在windws上 nging service install 命令创建的服务根本没法启动，前段时期我跟你说过此事情，在另一个issuse里边https://github.com/admpub/nging/issues/474

我在windows10上面用这个命令正常。
现在的版本跟以前相比还有一个改变就是强制需要管理员权限执行命令。如果你以前不是以管理员身份执行的 nging service install 命令，那现在可以试一下

**Comment by chendx-github** [comment]
你在windows10上面测试过可以实现指定用户运行吗？

**Comment by admpub** [comment]
> 你在windows10上面测试过可以实现指定用户运行吗？

是的，我就是在windows10开发和测试这部分功能的

**Comment by admpub** [comment]
> 你在windows10上面测试过可以实现指定用户运行吗？

@chendx-github  抱歉，前面的版本对 Windows 的服务这部分功能还是有问题，已经发布 v5.1.3 版修复，欢迎升级验证

**Comment by chendx-github** [comment]
经过测试  指定用户启动的功能还是不可以

**Comment by chendx-github** [comment]
windows上面的指定用户启动还是不可以

**Comment by chendx-github** [comment]
指定的是域用户
