### ISSUE TITLE
[BUG] 获取ip 不准

### ISSUE THREAD

**Issue by liang-hiwin** [admpub/nging#623]
**问题描述**
当软路由挂代理时，获取wan 的ip 为代理的ip，网络环境为 爱快拨号并且分配dhcp----旁路由openwrt 挂代理，

debian 12 x64 系统安装在PVE中，同理爱快，openwrt也是安装在PVE中。

**系统类型和版本:**
debian 12 x64

**Comment by admpub** [comment]
@liang-hiwin 你是指 ddns 功能吗？

**Comment by admpub** [comment]
@liang-hiwin 可以试试 v5.1.2-beta2 : https://dl.webx.top/nging/v5.1.2-beta2/

**Comment by liang-hiwin** [comment]
> @liang-hiwin你是指ddns功能吗？ 挂代理之后请求API获取接口的出口IP不就是代理的IP了，这种情况不应该采用API的方式来获取IP，不适合这种场景，如果自己可以通过写shell脚本获取到，可以使用命令行的方式执行脚本获取

对呀

**Comment by admpub** [comment]
所述问题非 bug，话题关闭
