### ISSUE TITLE
[BUG] DDNS 使用Cloudflare 解析ipv6 不生效【换成ddns-go 可以正常工作】

### ISSUE THREAD

**Issue by Avey777** [admpub/nging#624]
**问题描述**
nging的ddns没有像ddns-go一样生成解析日志，目前并不知道是否有正确获取到ip地址

**截图**
![image](https://github.com/admpub/nging/assets/35259040/efe7d860-a55d-4a57-ada2-b50514e6246a)

**系统类型和版本:**
 - 64位windows10

**数据库类型和版本:**
 - sqllite3

**其它相关信息**
无论是通过ip获取地址，还是通过网卡获取地址，都不能正常工作。
并且没有任何信息反馈

**Comment by admpub** [comment]
经过我验证，这个问题已经修复，话题先关闭。如果还有问题可重新打开。
