### ISSUE TITLE
[BUG] windows启动设置完管理员后无法登录

### ISSUE THREAD

**Issue by flyinke** [admpub/nging#663]
**问题描述**
启动设置完管理员后无法登录

**系统类型和版本:**
 - 64位windows11

**数据库类型和版本:**
 - sqlite

**日志提示**
:200: 2023-11-29T08:48:17+08:00 ::1 POST http localhost:9999 /login 14.3527ms 65
32228|2023-11-29 08:48:17|Error|app|failed to GetLastLoginInfo: db: no more rows in this result set
32228|2023-11-29 08:48:17|Warn|app|用户“admin”的会话环境发生改变，需要重新登录
:200: 2023-11-29T08:48:17+08:00 ::1 GET http localhost:9999 /index 1.9749ms 0
:200: 2023-11-29T08:48:17+08:00 ::1 GET http localhost:9999 /login 1.0934ms 6984

**Comment by flyinke** [comment]
这是日志。已经换电脑试了，可以复现，管理员密码肯定是正确的。
[nging日志.txt](https://github.com/admpub/nging/files/13495038/nging.txt)

**Comment by admpub** [comment]
程序已经更新，重新下载 v5.3.0 版本 覆盖即可
