### ISSUE TITLE
[BUG]5.2.6验证码

### ISSUE THREAD

**Issue by r1172464137** [admpub/nging#676]
**问题描述**
这里输入问题描述
5.2.6新安装登录的时候不跳验证码，提示 不支持验证码类型（5.2.5和5.3.1没问题（不是数据库，两种数据库都试过了））

**重现步骤**
重现步骤如下:
1. 安装
2. 登录
3. 不跳验证码

**期望的正确结果**
有验证码

**截图**
真别截了，反反复复安装好几次了

**系统类型和版本:**
 - debian11

**数据库类型和版本:**
 - sqlite

**其它相关信息**
输入有关此问题的其它说明

**Comment by admpub** [comment]
谢谢反馈，目前已经修复，麻烦重新下载此版本覆盖

**Comment by r1172464137** [comment]
还有提个建议，能不能增加ufw或者firewalld作为防火墙管理软件，iptables和nftables看的头大，而且前两者比后俩操作简单的多

**Comment by r1172464137** [comment]
👌
