### ISSUE TITLE
[BUG]为何我使用dockers安装启动后，一直重启呢

### ISSUE THREAD

**Issue by 18200994473** [admpub/nging#705]
**问题描述**
docker启动一直处于Restarting

**重现步骤**
重现步骤如下:
1. 下载docker-compose-sqlite.yml至/nging
2. 执行 docker-compose -f ./docker-compose-sqlite.yml up --build -d
3. 出现错误
4. 打开ip:9999出现503

**期望的正确结果**
正常使用

**截图**
![image](https://github.com/admpub/nging/assets/32983249/19d00d2b-5285-4ebc-a8c3-7eebf318011b)
![image](https://github.com/admpub/nging/assets/32983249/02dc7a0d-8ae2-46f9-8549-51f0ab9ae363)

**系统类型和版本:**
 - ubuntu-docker

**数据库类型和版本:**
 - sqllite

**其它相关信息**
是否在执行过程中有误呢？

**Comment by admpub** [comment]
感谢反馈，经过核实，这是一个bug，现在已经修复，请执行命令 `docker pull admpub/nging:latest` 更新镜像后重新操作。
