### ISSUE TITLE
[feature] 添加反向代理配置项

### ISSUE THREAD

**Issue by HartleyLau** [admpub/nging#716]
找了一圈，似乎只有Proxy部分的内容，希望能够增加reverse_proxy这个功能的配置项

**Comment by HartleyLau** [comment]
抱歉，发现label设置错了，应该为[feature]

**Comment by admpub** [comment]
https://www.coscms.com/article/10.html

**Comment by HartleyLau** [comment]
经过测试，结果如下：
nging地址:aaa.com
代理端口:1234

proxy路径: /
proxy地址: http://www.bbb.com:2345

访问aaa.com:1234 浏览器会直接跳转到http://www.bbb.com:2345，理论上，反向代理应实现的功能应该是浏览器不跳转，但是内容是由bbb.com:2345提供的，浏览器所有访问的路径应该还是aaa.com:1234

**Comment by admpub** [comment]
反向代理的确不会有跳转的处理，应该是网站程序自己进行的跳转，你可以检查一下自己的代码
