### ISSUE TITLE
mysql数据导出功能无效

### ISSUE THREAD

**Issue by 4867896** [admpub/nging#80]
mysql数据导出功能无效，点导出无反应。
顺便问下，可以集成mongodb数据导入导出功能么。
欢迎使用 Nging v3.0.2 licensed
BUILD: 20201023190842
COMMIT: 69dbc791762706c10885fff7fdb3f05d19566b36

**Comment by admpub** [comment]
导出功能采用的是mysql自带的mysqldump命令来处理的。所以必须确保mysqldump有效，否则将无法导出。
也就是说必须在环境变量PATH中登记mysqldump可执行程序的路径，以确保可以在系统中直接执行mysqldump命令
